apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-mspr2
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s
