{
 "title": "Exercises Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Nombre d'exercices par muscle",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as nbr_body_part_exercises, body_part FROM \"Data\".exercises\r\nGROUP BY body_part;"
    }
   ]
  },
  {
   "title": "Nombre d'exercices par catégorie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as nbr_exercises_by_category, category FROM \"Data\".exercises\r\nGROUP BY category "
    }
   ]
  },
  {
   "title": "Nombre d'exercices par niveau de difficulté",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as nbr_exercises_by_difficulty, difficulty FROM \"Data\".exercises\r\nGROUP BY difficulty "
    }
   ]
  },
  {
   "title": "Nombre d'exercices par équipement",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as nbr_exercises_by_equipment, equipment FROM \"Data\".exercises\r\nGROUP BY equipment;"
    }
   ]
  }
 ]
}