{
 "title": "Foods Quality",
 "time": { "from": "2026-03-31T04:35:40.929Z", "to": "2026-04-16T04:35:40.929Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Nombre de nourriture par type d'aliment",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as number_by_category, food_categories.name FROM \"Data\".foods as foods\r\nINNER JOIN \"Data\".food_categories as food_categories on foods.food_category_id = food_categories.id\r\nGROUP BY food_category_id, food_categories.name;"
    }
   ]
  },
  {
   "title": "Pourcentage de données alimentaires dont le water_intake_mlest nul.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT (COUNT(*) * 100) / (SELECT COUNT(*) FROM \"Data\".foods) as PERCENTAGE FROM \"Data\".foods\r\nWHERE water_intake_ml is null"
    }
   ]
  },
  {
   "title": "Pourcentage de données alimentaires dont le food_category_id est nul.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT (COUNT(*) * 100) / (SELECT COUNT(*) FROM \"Data\".foods) as PERCENTAGE FROM \"Data\".foods\r\nWHERE food_category_id is null"
    }
   ]
  }
 ]
}