{
 "title": "Users Quality",
 "time": { "from": "2026-03-31T04:35:40.929Z", "to": "2026-04-16T04:35:40.929Z" },
 "panels": [
  {
   "title": "Nombre d'emails dupliqués",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*), email FROM \"Data\".users\r\nGROUP BY email\r\nHAVING COUNT(*) > 1 "
    }
   ]
  },
  {
   "title": "Utilisateur sans poids",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT (COUNT(*) * 100) / (SELECT COUNT(*) FROM \"Data\".users) as PERCENTAGE FROM \"Data\".users\r\nWHERE weight_kg is null;"
    }
   ]
  },
  {
   "title": "Taille anormale des utilisateurs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) FROM \"Data\".users\r\nWHERE height_cm < 50 OR height_cm > 250"
    }
   ]
  },
  {
   "title": "Utilisateurs premium",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT (COUNT(*) * 100) / (SELECT COUNT(*) FROM \"Data\".users) as PERCENTAGE FROM \"Data\".users\r\nWHERE is_premium = true"
    }
   ]
  },
  {
   "title": "Poids d'utilisateur anormaux",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) FROM \"Data\".users\r\nWHERE weight_kg < 0 OR weight_kg > 300"
    }
   ]
  },
  {
   "title": "Age d'utilisateur anormaux",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) FROM \"Data\".users\r\nWHERE age < 0 OR age > 120"
    }
   ]
  },
  {
   "title": "Tranche d'âge des utilisateurs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as users_under_14 FROM \"Data\".users\r\nWHERE age >= 0 AND age <= 14"
    },
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as users_between_15_and_64 FROM \"Data\".users\r\nWHERE age >= 15 AND age <= 64"
    },
    {
     "dataset": "healthai",
     "rawSql": "SELECT COUNT(*) as users_more_65 FROM \"Data\".users\r\nWHERE age >= 65"
    }
   ]
  }
 ]
}